CalorieCounter/Pages/Create.cshtml.cs
using CalorieCounter.Data;
using CalorieCounter.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using SQLitePCL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace CalorieCounter.Pages
{
    public class CreateModel : PageModel
    {
        private readonly CalorieCounter.Data.DishDbContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<User> _userManager;


        public CreateModel(CalorieCounter.Data.DishDbContext context, UserManager<User> userManager, IWebHostEnvironment environment)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
        }

        public IActionResult OnGet()
        {

            return Page();

        }

        [BindProperty]
        public DishViewModel Input { get; set; } = new();

        public DishViewModel RecommendedDish { get; set; } = new DishViewModel(); // single dish
        public string reccDishimg = "";

        // For more information, see https://aka.ms/RazorPagesCRUD.
        //
        
        public async Task<IActionResult> OnPostEmbedDishesAsync()
        {
            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var dishTexts = await _context.Dishes
    .Where(d => d.User.Id == userID)
    .Select(d =>
        "Name: " + d.Name +
        ", Category: " + d.Category +
        ", Description: " + d.Description +
        ", Ingredients: " + d.Ingredients)
    .ToListAsync();

            foreach (var text in dishTexts)
            {
                Console.WriteLine(text);
            }
            var json = JsonSerializer.Serialize(dishTexts);
            using var client = new HttpClient();
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await client.PostAsync("http://localhost:5000/Create/embeddishes", content);
            var json1 = await response.Content.ReadAsStringAsync();
            Console.WriteLine(json1);

            // Replace invalid NaN tokens with null
            var safeJson = json1.Replace("NaN", "null");

            // Parse JSON 
            using var doc = JsonDocument.Parse(safeJson);
            var root = doc.RootElement;
            RecommendedDish.Name = root.GetProperty("Name").GetString();
            RecommendedDish.Description = root.GetProperty("Description").GetString();
            RecommendedDish.Category = root.GetProperty("Category").GetString();
            RecommendedDish.Ingredients = root.GetProperty("Ingredients").GetString();
            reccDishimg = root.GetProperty("Image").GetString();
            string html = $@"
            <div class='card shadow border-0'>
            <img src='{reccDishimg}' class='card-img-top' alt='{RecommendedDish.Name}' />
            <div class='card-body'>
                <h4 class='card-title'>{RecommendedDish.Name}</h4>
                <p><strong>Category:</strong> {RecommendedDish.Category}</p>
                <p><strong>Ingredients:</strong> {RecommendedDish.Ingredients}</p>
                <p>{RecommendedDish.Description}</p>
            </div>
        </div>";
            Console.WriteLine("Returning HTML: " + html);
            return Content(html, "text/html");




          
        }



        public async Task<IActionResult> OnPostAsync()
        {

            if (!ModelState.IsValid)
            {
                return Page();
            }
            var dish = new Dish
            {
                Name = Input.Name,
                Description = Input.Description,
                Ingredients = Input.Ingredients,
                Category = Input.Category,
                User = await _userManager.FindByIdAsync(User.FindFirstValue(ClaimTypes.NameIdentifier))

            };
            _context.Add(dish);
            await _context.SaveChangesAsync();
            var lastDishId = dish.Id;
            if (Input.Image != null)
            {
                foreach (var file in Input.Image)
                {
                    if (file != null && file.Length > 0)
                    {

                        var filePath = Path.Combine(_environment.WebRootPath, "Images/", file.FileName);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                            stream.Close();
                        }

                        var dishImage = new DishImage
                        {
                            DishID = lastDishId,
                            ImageString = file.FileName,
                            ImageUrl = filePath
                        };

                        _context.DishImages.Add(dishImage);
                        await _context.SaveChangesAsync();
                    }
                }
               
            }
            return RedirectToPage("./Index");
        }
    }
}

CalorieCounter/Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using CalorieCounter.Data;
using CalorieCounter.Models;

namespace CalorieCounter.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly CalorieCounter.Data.DishDbContext _context;

        public DeleteModel(CalorieCounter.Data.DishDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Dish Dish { get; set; } = default!;
        public List<DishImage> DishImages { get; set; } = default!;
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes.FirstOrDefaultAsync(m => m.Id == id);

            if (dish == null)
            {
                return NotFound();
            }
            else
            {
                Dish = dish;
                DishImages = await _context.DishImages
               .Where(img => img.DishID == Dish.Id)
               .ToListAsync();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish = await _context.Dishes.FindAsync(id);
//Inefficient plaster written at 2am, optimize later
            var dishImages = await _context.DishImages
    .Where(img => img.DishID == id)
    .ToListAsync();
            if (dish != null && dishImages != null)
            {
                Dish = dish;
                _context.Dishes.Remove(Dish);
                _context.DishImages.RemoveRange(dishImages);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

CalorieCounter/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CalorieCounter.Data;
using CalorieCounter.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using System.Reflection.Metadata;
using Microsoft.Extensions.Hosting;

namespace CalorieCounter.Pages
{
    public class EditModel : PageModel
    {
        private readonly CalorieCounter.Data.DishDbContext _context;
        private readonly IWebHostEnvironment _environment; 

        public EditModel(IWebHostEnvironment environment, CalorieCounter.Data.DishDbContext context)
        {
            _context = context;
            _environment = environment;
        }

        [BindProperty]
        public Dish Dish { get; set; } = default!;
        public List<DishImage> DishImages { get; set; } = default!;
//Insert the images into view model
        [BindProperty]
        public DishViewModel Input {  get; set; } = default!;
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dish =  await _context.Dishes.FirstOrDefaultAsync(m => m.Id == id);

            if (dish == null)
            {
                return NotFound();
            }
            Dish = dish;
            //Fetch images 
            DishImages = await _context.DishImages
                .Where(img => img.DishID == Dish.Id)
                .ToListAsync();
            return Page();
        }
        public async Task<IActionResult> OnPostDeleteImageAsync(int imageId, int dishId)
        {
            var image = await _context.DishImages.FirstOrDefaultAsync(i => i.DishImageId == imageId);
            if (image != null) { 
                _context.DishImages.Remove(image);
                await _context.SaveChangesAsync();
                

            }
            DishImages = await _context.DishImages.Where(i => i.DishID == Dish.Id).ToListAsync();
            TempData["ToastMessage"] = "Your Image was deleted successfully";
            TempData["ToastType"] = "success";
            
            return RedirectToPage("/Edit" ,new { id = dishId });
        }
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
       
        public async Task<IActionResult> OnPostCreateNewImageAsync(int id)
        {
            var dish = await _context.Dishes.FirstOrDefaultAsync(m => m.Id == id);

         
            foreach (var file in Input.Image)
            {
                if (file != null && file.Length > 0)
                {

                    var filePath = Path.Combine(_environment.WebRootPath, "Images/", file.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                        stream.Close();
                    }
                    var newDishImage = new DishImage
                    {
                        DishID = dish.Id,
                        ImageString = file.FileName,
                        ImageUrl = filePath
                    };
                    
                    _context.DishImages.Add(newDishImage);
                    await _context.SaveChangesAsync();
                    DishImages = await _context.DishImages.Where(i => i.DishID == Dish.Id).ToListAsync();
                }
                
            }
            return RedirectToPage("/Edit", new { id = id });
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {

                return Page();
            }

            var dishInDb = await _context.Dishes.FindAsync(Dish.Id);
            
            dishInDb.Name = Dish.Name;
            dishInDb.Description = Dish.Description;
            await _context.SaveChangesAsync();
            DishImages = await _context.DishImages
                .Where(img => img.DishID == Dish.Id)
                .ToListAsync();
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DishExists(Dish.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            if (DishImages != null) {
                return RedirectToPage("./Index");
            }
            return Page();
            
        }

        private bool DishExists(int id)
        {
            return _context.Dishes.Any(e => e.Id == id);
        }
    }
}

CalorieCounter/Pages/Friends.cshtml.cs
using CalorieCounter.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging.Signing;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Linq;

namespace CalorieCounter.Pages
{
    public class FriendsModel : PageModel
    {
        private readonly CalorieCounter.Data.DishDbContext _context;
        private readonly UserManager<User> _userManager;
        public FriendsModel(UserManager<User> userManager, CalorieCounter.Data.DishDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }
        public List<Friendship> FriendsList { get; set; } = default!;
        public string ProfilePictureUrl = "";
        [BindProperty]
        public string NewFriendName { get; set; }
        [BindProperty]
       
        public string EmailAddress { get; set; }
        [TempData]
        public string StatusMessage { get; set; }
        public List<Friendship>? PendingRequestsSent { get; set; }
        public List<Friendship>? PendingRequestsRecieved { get; set; }
        public List<User>? Friends { get; set; }


        public async Task OnGetAsync()
        {
          
            string? userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userID != null) {
                var user = await _context.Users
                .Include(u => u.Inviters)
                .ThenInclude(f => f.User2)      // Load the other user in the friendship from Inviters
                .Include(u => u.Invitees)
                .ThenInclude(f => f.User1)      // Load the otheruser in the friendship from Invitees
                .FirstOrDefaultAsync(u => u.Id == userID);
                ProfilePictureUrl = user.ProfilePicturePath;
                //pic
                Friends = await _context.Friendships.Where(f => (f.User1Id == userID || f.User2Id == userID) && f.Status == FriendshipStatus.Accepted).Include(f => f.User1).Include(f => f.User2).Select(f => f.User1Id == userID ? f.User2 : f.User1).ToListAsync();

                if (user.Inviters != null)
                {
                    PendingRequestsSent = user.Inviters.Where(f => f.Status == FriendshipStatus.Pending).ToList();
                }
                if (user.Invitees != null)
                {
                    PendingRequestsRecieved = user.Invitees.Where(f => f.Status == FriendshipStatus.Pending).ToList();
                }
               
            }
            
            
        }
        public async Task<IActionResult> OnPostAddFriendAsync()
        {
            // optimize later (make the code above reusable) 

            string? userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userID);
            User friend = default;

            if (userID != null)
            {
                if (!string.IsNullOrEmpty(EmailAddress))
                {
                    friend = await _userManager.FindByEmailAsync(EmailAddress);
                }
                else
                {
                    friend = await _context.Users.FirstOrDefaultAsync(m => m.NickName == NewFriendName);
                }

               

              

                if (friend != null)
                {
                  
                    Friendship newRequest = new Friendship
                    {
                        User1Id = userID,
                        User1 = user,
                        User2Id = friend.Id.ToString(),
                        User2 = friend,
                        Status = FriendshipStatus.Pending

                    };
                    user.Inviters.Add(newRequest);
                    friend.Invitees.Add(newRequest);
                    _context.Friendships.Add(newRequest);
                    await _context.SaveChangesAsync();
                    ProfilePictureUrl = user.ProfilePicturePath;
                   
          

               
                    StatusMessage = "Request has been sent";
                    return Page();
                }

            }  
            StatusMessage = "No such user exists";
            return RedirectToPage();
           
        }
       public async Task<IActionResult> OnPostAcceptAsync(string user1Id, string user2Id)
        {
            var friendship = await _context.Friendships
        .FirstOrDefaultAsync(f => f.User1Id == user1Id && f.User2Id == user2Id);

            if (friendship == null) return NotFound();
            friendship.Status = FriendshipStatus.Accepted;
            await _context.SaveChangesAsync();

            return RedirectToPage();
        }
    }
}

CalorieCounter/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CalorieCounter.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

CalorieCounter/Pages/Social.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CalorieCounter.Pages
{
    public class SocialModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CalorieCounter/Pages/Create.cshtml
@page
@model CalorieCounter.Pages.CreateModel

@{
    ViewData["Title"] = "Create";
}

<form id="dummyForm">
    @Html.AntiForgeryToken()
</form>

<link rel="stylesheet" href="~/css/createdish.css" />
<div class="row">
    <div class="col-md-6">
        <div class="d-flex justify-content-between align-items-center">
            <div class="title-heading">Create Dish</div>

            <button id="generateBtn" type="button" class="btn btn-success rounded-pill px-4" data-bs-toggle="modal" data-bs-target="#recipeModal">
                    Generate a Recipe
                </button>
         
     
        </div>

     </div>

        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Input.Name"></label>
                <input asp-for="Input.Name" class="form-control" />
                <span asp-validation-for="Input.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Input.Description"></label>
                <input asp-for="Input.Description" class="form-control" />
                <span asp-validation-for="Input.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Input.Category"></label>
                <input asp-for="Input.Category" class="form-control" />
                <span asp-validation-for="Input.Category" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Input.Ingredients"></label>
                <input asp-for="Input.Ingredients" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Input.Image"></label>
                <input asp-for="Input.Image" type="file" class="form-control" />
            </div>

            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary w-100" />
            </div>

            <div class="mt-2">
                <a asp-page="./Index" class="text-info">Back to List</a>
            </div>
        </form>

</div>

<div class="modal fade" id="recipeModal" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content bg-dark text-white border-0 glassy-card">
            <div class="modal-header border-0">
                <h5 class="modal-title">Generated Recipe</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="recipeModalBody">
                <!-- recipe content injected here -->
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-success">Add</button>
                <button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
<style>
    .glassy-card {
        background-color: rgba(0, 0, 0, 0.7);
        color: white;
        backdrop-filter: blur(8px); 
    }

        .glassy-card .card-body {
            background-color: rgba(0, 0, 0, 0) ;
        }

    .card-body {
        background-color: rgba(0, 0, 0, 0) ;
        color:white;
    
    }
    .card {
        background-color: rgba(0, 0, 0, 0) ;
    }
</style>
<script>

        document.getElementById("generateBtn").addEventListener("click", async function (e) {
        e.preventDefault(); 
            console.log("Button clicked! JS is running");
            const token = document.querySelector('input[name="__RequestVerificationToken"]').value;
            const response = await fetch("/Create?handler=EmbedDishes", {
                method: "POST",
                headers: {
                    "RequestVerificationToken": token 
                }
                
            });

            const html = await response.text();
            document.getElementById("recipeModalBody").innerHTML = html;

            const modalEl = document.getElementById('recipeModal');
            const recipeModal = new bootstrap.Modal(modalEl);

   
            recipeModal.show();
            
            modalEl.addEventListener('hidden.bs.modal', () => {
        const backdrop = document.querySelector('.modal-backdrop');
        if (backdrop) backdrop.remove();
    });
       
    });

</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CalorieCounter/Pages/Edit.cshtml
@page
@model CalorieCounter.Pages.EditModel

@{
    ViewData["Title"] = "Edit";
}
<head>
    <link rel="stylesheet" href="~/css/editstyle.css" />
</head>
<h1>Edit</h1>

<h4>Dish</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Dish.Id" />
            <div class="form-group">
                <label asp-for="Dish.Name" class="control-label"></label>
                <input asp-for="Dish.Name" class="form-control" />
                <span asp-validation-for="Dish.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dish.Description" class="control-label"></label>
                <input asp-for="Dish.Description" class="form-control" />
                <span asp-validation-for="Dish.Description" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div class="image-row">
            @foreach (var img in Model.DishImages)
            {
               
                <form method="post" asp-page-handler="DeleteImage" >
                <div class="image-wrapper">
                    <!-- Optimistic UI update, include server side verification later-->
                      <!--Pass ID-->
                    <input type="hidden" name="imageId" value="@img.DishImageId" />
                    <input type="hidden" name="dishId" value="@img.DishID" />
                    <button class="close-btn">&times;</button>
                    
                    <img src="~/Images/@img.ImageString">
                </div>
                </form>
            }
            <form method="post" asp-page-handler="CreateNewImage"  enctype="multipart/form-data">
            <div class="addImage">
                    <input type="hidden"  name="id" value="@Model.DishImages[0].DishID" />
                    <input asp-for="Input.Image" id="Images" type="file" multiple />
                    
            </div>
                <div class="form-group">
                    
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CalorieCounter/Pages/Friends.cshtml
@page
@model CalorieCounter.Pages.FriendsModel
@using System.Security.Claims

@{
    var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}
@{
    Layout = "/Pages/Shared/_Layout.cshtml";
    ViewData["Title"] = "Home Page";
    ViewData["ProfilePictureUrl"] = Model.ProfilePictureUrl;
}
<head>
    <style href="~/friendsdesign.css"></style>
</head>
<form id="dummyForm">
    @Html.AntiForgeryToken()
</form>
<ul class="nav nav-tabs border-0" id="friendTabs" role="tablist">
 
   
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="all-tab" data-bs-toggle="tab" data-bs-target="#all" type="button" role="tab">All</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pending" type="button" role="tab">Pending</button>
    </li>
   
    <button class="btn add-friend-btn" data-bs-toggle="modal" data-bs-target="#addFriendModal">Add Friend</button>
</ul>




<div class="tab-content mt-3" id="friendTabsContent">
  
    
    <div class="tab-pane fade show active" id="all" role="tabpanel">

        <p>All friends</p>
        @if (Model.Friends != null)
        {
            <ul class="list-group">
                @foreach (var request in Model.Friends)
                {
                    <li class="list-group-item bg-dark text-white rounded d-flex align-items-center justify-content-between mb-2">
                        <div class="d-flex align-items-center gap-3">
                        <img src="@request.ProfilePicturePath" class="rounded-circle" style="width: 40px; height: 40px; object-fit: cover;" />
                        <span class="fw-semibold">@request.NickName</span>
                    
                    </div>
                        <button class="btn btn-outline-light btn-sm star-btn">
                            <i class="bi bi-star"></i>
                        </button>
                    </li>
                }
        </ul>
        }
    </div>
    <div class="tab-pane fade" id="pending" role="tabpanel">
        <h5>Pending Requests</h5> 
        @if (Model.PendingRequestsRecieved != null)
        {
            <ul class="list-group">
                @foreach (var request in Model.PendingRequestsRecieved)
                {
                    <li class="list-group-item bg-dark text-white rounded d-flex align-items-center justify-content-between mb-2">
                    <div class="d-flex align-items-center gap-3">
                        <img src="@request.User1.ProfilePicturePath" class="rounded-circle" style="width: 40px; height: 40px; object-fit: cover;" />
                        <span class="fw-semibold">@request.User1.NickName</span>
                    
                    </div>
                        <form method="post" asp-page-handler="Accept" style="display:inline;">
                            <input type="hidden" name="user1Id" value="@request.User1Id" />
                            <input type="hidden" name="user2Id" value="@request.User2Id" />
                            <button type="submit" class="btn btn-success btn-sm">Accept</button>
                        </form>
                        <form method="post" asp-page-handler="Reject" style="display:inline; margin-left:5px;">
                            <input type="hidden" name="user1Id" value="@request.User1Id" />
                            <input type="hidden" name="user2Id" value="@request.User2Id" />
                            <button type="submit" class="btn btn-danger btn-sm">Reject</button>
                        </form>
                    </li>
                }
            </ul>
        }
        else
        {
            <p class="text-muted">No pending friend requests.</p>
        }
    </div>
</div>
   
</div>
<div class="modal fade" id="addFriendModal" tabindex="-1" aria-labelledby="addFriendModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content text-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="addFriendModalLabel">Add Friend</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-page-handler="AddFriend"
            method="post">
                <div class="modal-body">
                    <div class="mb-3">
                        <h1> Choose one </h1>
                        <label asp-for="NewFriendName" class="form-label">Friend Username</label>
                        <input asp-for="NewFriendName" class="form-control" />
                        <span asp-validation-for="NewFriendName" class="text-danger"></span>
                        <label asp-for="EmailAddress" class="form-label">Email address</label>
                        <input asp-for="EmailAddress" class="form-control" />
                        <span asp-validation-for="EmailAddress" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="favToast" class="toast text-bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body" style="color:black">
                ✅ User added to favorites
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>
<script>
      document.querySelectorAll('.star-btn').forEach(btn => {
      btn.addEventListener('click', function () {
        const icon = this.querySelector('i');
        icon.classList.toggle('bi-star');
        icon.classList.toggle('bi-star-fill');

        if (icon.classList.contains('bi-star-fill')) {
          
          const toastEl = document.getElementById('favToast');
          const toast = new bootstrap.Toast(toastEl);
          toast.show();
        }
      });
    });
</script>
@if (Model.StatusMessage != null)
{
    <div class="alert alert-success mt-3">@Model.StatusMessage</div>
}
    </div>